name: Cookie
description:
  Cookie is a mobile application that allows users convert google play credit to cash.

publish_to: "none"

version: 28.0.0+28

environment:
  sdk: ">=2.17.0-0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4
  dio: ^5.0.3
  shared_preferences: ^2.0.20
  in_app_purchase: ^3.1.5
  intl: ^0.18.0
  google_sign_in: ^6.0.2
  sign_button: ^2.0.3
  webview_flutter: ^4.0.7
  url_launcher: ^6.1.10
  timeline_tile: ^2.0.0
  unity_ads_plugin: ^0.3.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
